### Generate a 1 x 90 day key with rank 2

POST http://localhost:80/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "command": "generate",
    "length": "90",
    "rank": "2",
    "quantity": "1"
}
### Show all users in Table

POST http://localhost:80/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "command": "show"
}

## Reset a users HWID
POST http://localhost:3000/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "command": "resethwid",
    "username":"testUser"
}
### Find a user by UUID4 License

POST http://localhost:80/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "command": "find",
    "entry": "b70ee420-4cd8-45cf-9593-9e2473e1a155"
}

### Redeem a license

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "command": "redeem",
    "username":"test1234",
    "password":"1234",
    "hwid":"ZLQ1893010fQPUI31083",
    "license": "9cdfa6bf-0fb0-4fba-aad8-5fc841744c2d"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "command": "resethwid",
    "username":"test123",
    "password": "1234"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "command": "resetpw",
    "username":"testnpo",
    "license": "680a385e-4477-4171-a722-9de97aad024d",
    "newPassword":"12345"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "command": "login",
    "username":"test1234",
    "password":"1234",
    "hwid":"ZLQ1893010fQPUI31083"
}
###

GET http://localhost:80/ 
