###

POST http://localhost:3000/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "a": "show",
    "length": "90",
    "rank": "2",
    "quantity": "5"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "a": "database"
}
###

GET http://localhost:3000/ 
