###

POST http://localhost:3000/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "a": "generate",
    "length": "90",
    "rank": "2",
    "quantity": "1"
}
###
POST http://localhost:3000/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "a": "resethwid",
    "username":"testUser"
}
###

POST http://localhost:3000/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "a": "find",
    "entry": "ac41f195-6590-4d27-baf4-512d66900ec9"
}
###

POST http://localhost:3000/admin HTTP/1.1
content-type: application/json
Authorization: API_TOKEN

{
    "a": "find",
    "entry": "680a385e-4477-4171-a722-9de97aad024d"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "a": "redeem",
    "username":"testUser",
    "password":"1234",
    "hwid":"ZLQ1893010fQPUI31083",
    "license": "ac41f195-6590-4d27-baf4-512d66900ec9"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "a": "resetpw",
    "username":"testnpo",
    "license": "680a385e-4477-4171-a722-9de97aad024d",
    "newPassword":"12345"
}
###

POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "a": "login",
    "username":"testUser",
    "password":"1234",
    "hwid":"ZLQ1893010fQPUI31083"
}
###

GET http://localhost:3000/ 
